% Main Func Call %
out = heat_transfer_2d_solver('steel','DUPLEX','tCr_um',50, ...
                              'Nr',240*4,'Nz',120, ...
                              'dt_fd',1e-4,'tEnd_fd',20e-3, ...
                              'debug',true,'debug_stride',10);
